"""Generate clinician-voice questions for every chunk: document-side expansion.

The problem this attacks
------------------------
The held-out set measured retrieval swinging from nDCG 0.90 to 0.38 on identical
content, depending only on whether the question used guideline vocabulary. The audit of
the failures named the mechanism: a clinician asks "is a flozin worth starting?" and the
word "flozin" appears nowhere in either guideline; asks about a "vomiting bug" where
KDIGO writes "acute, dehydrating illness"; asks about "sitting around all day" where it
writes "sedentary behavior".

Query-side fixes were tried and rejected. HyDE put an LLM call on the query path and did
not clear its confidence interval. MedCPT swapped the encoder for one trained on real
user queries and left the same eight questions failing - the gap is not in the embedding
space, it is that the colloquial term is absent from the corpus.

Document expansion puts the missing vocabulary into the index instead, generated once
and cached, costing nothing at query time. This is docTTTTTquery's term-injection
effect: adding terms relevant to a passage but not present in it.

What this is not
----------------
The corpus already carries a `hype_questions` field. That is NOT this. Those are
template-generated by `build_hype_questions(chunk_type, topics, text, label)` - 560
distinct strings across 3106 instances, one of them repeated 572 times - and they are
keyed on the chunk's topic labels. EVALUATION.md already excludes topic labels from
scoring because the retriever boosts on them and scoring with them is circular;
indexing them would put that circularity back. They are also, being templates, written
in the same formal register as the guideline, so they cannot bridge a register gap.

Cost control
------------
1479 chunks one per call at a free tier's pace is hours. Chunks are batched, so it is
roughly 185 calls - about 20 minutes at 10 rpm. Resumable: anything already cached is
skipped, so an interrupted run is picked up rather than restarted.

Usage:
    python scripts/build_doc2query.py --rpm 10
    python scripts/build_doc2query.py --limit 24 --verbose    # try it on a few first
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.error
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from nephrolex.paths import CORPUS, DATA  # noqa: E402

CACHE = DATA / "doc2query.jsonl"

# Asking for register explicitly, and against the passage's own wording, because the
# whole value here is the words the passage does NOT contain. A model left to itself
# paraphrases the source and adds nothing an index did not already have.
PROMPT = """You are helping build a search index over CKD clinical guidelines.

For each passage below, write {k} questions that a busy clinician would actually type or
say at the point of care, and that this passage answers.

Rules:
- Write how a doctor talks to a colleague, not how a guideline is written. Use everyday
  phrasing, drug-class shorthand, and abbreviations where a clinician naturally would
  ("a flozin", "an ACE", "water tablets", "a vomiting bug", "bloods").
- Deliberately AVOID the passage's own formal wording. If the passage says "sedentary
  behavior", ask about "sitting around all day". If it says "acute, dehydrating illness",
  ask about "a stomach bug". The point is to add words the passage does not contain.
- Each question must be answerable from that passage alone.
- Keep each under 20 words. No numbering inside the question text.

Every passage must get exactly {k} questions. If a passage is a bare caption or is
mostly a pointer to something else, still write the questions a clinician would ask that
land on it - do not skip it and do not explain why.

Return ONLY lines of the form, one per question:
<passage number>|<question>

PASSAGES
{passages}"""

LINE_RE = re.compile(r"^\s*(\d+)\s*\|\s*(.+?)\s*$")


def load_cache() -> dict[str, list[str]]:
    cache: dict[str, list[str]] = {}
    if CACHE.exists():
        with CACHE.open("r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    row = json.loads(line)
                    # Last write wins, so a --retry-empty pass supersedes the
                    # empty row it is replacing without rewriting the file.
                    if row["questions"] or row["id"] not in cache:
                        cache[row["id"]] = row["questions"]
    return cache


def append(rows: list[tuple[str, list[str]]]) -> None:
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    with CACHE.open("a", encoding="utf-8") as f:
        for chunk_id, questions in rows:
            f.write(json.dumps({"id": chunk_id, "questions": questions},
                               ensure_ascii=False) + "\n")


def generate(batch: list[dict], k: int, chars: int) -> dict[str, list[str]]:
    from nephrolex.generation.generate import (DEFAULT_MODEL, available,
                                               call_anthropic, call_gemini)

    provider = available()
    if not provider:
        raise RuntimeError("no API key (GEMINI_API_KEY or ANTHROPIC_API_KEY)")

    passages = "\n\n".join(
        f"{i}. {' '.join(record['raw_text'].split())[:chars]}"
        for i, record in enumerate(batch, 1)
    )
    prompt = PROMPT.format(k=k, passages=passages)
    model = DEFAULT_MODEL[provider]
    # Room for k questions per passage across the batch.
    budget = 60 * k * len(batch) + 200
    text = (call_gemini(prompt, model, max_tokens=budget) if provider == "gemini"
            else call_anthropic(prompt, model, max_tokens=budget))

    out: dict[str, list[str]] = {}
    for line in text.splitlines():
        match = LINE_RE.match(line)
        if not match:
            continue
        index = int(match.group(1))
        if not 1 <= index <= len(batch):
            continue
        question = match.group(2).strip().strip('"')
        if question:
            out.setdefault(batch[index - 1]["id"], []).append(question)
    return out


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch", type=int, default=8, help="Passages per API call.")
    parser.add_argument("--k", type=int, default=3, help="Questions per passage.")
    parser.add_argument("--chars", type=int, default=700, help="Passage truncation.")
    parser.add_argument("--rpm", type=float, default=10.0)
    parser.add_argument("--limit", type=int, default=0, help="Only the first N chunks.")
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--retry-empty", action="store_true",
                        help="Re-attempt chunks previously cached with no questions, "
                             "at a smaller batch size.")
    args = parser.parse_args()

    from nephrolex.generation.generate import available

    if not available():
        raise SystemExit(
            "no API key. Set GEMINI_API_KEY or ANTHROPIC_API_KEY in this shell first."
        )

    with CORPUS.open("r", encoding="utf-8") as f:
        records = [json.loads(line) for line in f if line.strip()]
    if args.limit:
        records = records[: args.limit]

    cache = load_cache()
    if args.retry_empty:
        # A chunk cached with no questions was skipped by the model, not judged
        # unexpandable. Batching is what causes it - the model drops a passage from a
        # list of eight - so retry those alone, at a batch size where it cannot.
        todo = [r for r in records if not cache.get(r["id"])]
        args.batch = min(args.batch, 3)
        print(f"retry-empty: {len(todo)} chunks with no questions, batch {args.batch}")
    else:
        todo = [r for r in records if r["id"] not in cache]
    print(f"{len(records)} chunks | {len(records) - len(todo)} cached | {len(todo)} to do")
    if not todo:
        print("nothing to generate.")
        return
    batches = (len(todo) + args.batch - 1) // args.batch
    print(f"{batches} calls at {args.rpm} rpm ~ {batches / args.rpm:.0f} min\n")

    interval = 60.0 / max(args.rpm, 1)
    last = 0.0
    made = failed = 0
    reasons: dict[str, int] = {}

    for start in range(0, len(todo), args.batch):
        batch = todo[start:start + args.batch]
        wait = interval - (time.time() - last)
        if wait > 0:
            time.sleep(wait)

        result = None
        for attempt in range(3):
            try:
                last = time.time()
                result = generate(batch, args.k, args.chars)
                break
            except urllib.error.HTTPError as error:
                if error.code == 429:
                    if attempt == 2:
                        reasons["rate limited (retries exhausted)"] = \
                            reasons.get("rate limited (retries exhausted)", 0) + 1
                        break
                    header = error.headers.get("Retry-After") if error.headers else None
                    delay = float(header) if header and header.isdigit() else 20 * (attempt + 1)
                    print(f"  rate limited, waiting {delay:.0f}s")
                    time.sleep(delay)
                    continue
                reasons[f"HTTP {error.code}"] = reasons.get(f"HTTP {error.code}", 0) + 1
                break
            except Exception as error:  # noqa: BLE001
                reasons[type(error).__name__] = reasons.get(type(error).__name__, 0) + 1
                break

        if not result:
            failed += len(batch)
            continue

        # A passage the model skipped is cached as an empty list, so a resumed run does
        # not retry it forever; an empty expansion simply contributes nothing.
        rows = [(record["id"], result.get(record["id"], [])) for record in batch]
        append(rows)
        made += sum(1 for _, questions in rows if questions)
        if args.verbose:
            for chunk_id, questions in rows[:2]:
                for question in questions[:2]:
                    print(f"  {chunk_id[-26:]:<26} {question[:78]}")
        done = start + len(batch)
        if done % (args.batch * 10) < args.batch:
            print(f"  {done}/{len(todo)} chunks, {made} expanded", flush=True)

    print(f"\nexpanded {made}, failed {failed} -> {CACHE}")
    if reasons:
        print("failure reasons: " + ", ".join(f"{k} x{v}" for k, v in sorted(reasons.items())))
        print("re-run to fill the gaps; anything cached is skipped.")


if __name__ == "__main__":
    main()
