"""Turn licensed guideline PDFs into a searchable, citable corpus.

Run once per guideline revision. Everything it writes is derived from copyrighted
guideline text and stays on the operator's own storage -- see NOTICE.

    python scripts/build_corpus.py
    python scripts/build_corpus.py --skip-dense      # lexical only, much faster
    python scripts/build_corpus.py --ocr             # scanned or low-text PDFs

Replaces scripts/full_pipeline.ps1, which was Windows-only and had drifted: it
called two scripts that no longer exist and defaulted to an encoder this system
measured and rejected.

The stages are ordered by what depends on what, and each is skipped when its
output is already present and newer than its input, so re-running after an
interrupted build does not redo the expensive parts.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from newbieduo.paths import CHUNKS, CORPUS, DATA, INDEXES, RAW_PDFS  # noqa: E402

# The encoder this system actually ships. Named here rather than defaulted in
# each script, so a corpus cannot be built against one model and served by
# another - which happened once, and cost 0.064 nDCG before anything reported it.
DENSE_MODEL = "abhinand/MedEmbed-large-v0.1"


def run(label: str, args: list[str]) -> None:
    print(f"\n=== {label} ===", flush=True)
    started = time.time()
    result = subprocess.run([sys.executable, *args], cwd=ROOT)
    if result.returncode != 0:
        raise SystemExit(f"{label} failed with exit code {result.returncode}")
    print(f"--- {label} done in {time.time() - started:.1f}s", flush=True)


def require_pdfs() -> list[Path]:
    """Fail early and legibly when the operator has not supplied the guidelines."""
    pdfs = sorted(RAW_PDFS.glob("*.pdf")) if RAW_PDFS.exists() else []
    if not pdfs:
        raise SystemExit(
            f"No PDFs found in {RAW_PDFS}.\n\n"
            "This repository does not ship the guidelines: KDIGO 2024 and NICE NG203\n"
            "are copyrighted and are licensed to you, not to us. Place your own copies\n"
            "there and run this again. See README.md, 'Build the corpus'."
        )
    for pdf in pdfs:
        print(f"  found {pdf.name}  ({pdf.stat().st_size / 1e6:.1f} MB)")
    return pdfs


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--skip-dense", action="store_true",
                        help="Lexical index only. Retrieval works but scores ~0.08 nDCG lower.")
    parser.add_argument("--ocr", action="store_true",
                        help="Enable Docling OCR, for scanned or low-text PDFs.")
    parser.add_argument("--force", action="store_true",
                        help="Rebuild every stage even if its output exists.")
    args = parser.parse_args()

    print(f"data root : {DATA}")
    print(f"pdfs      : {RAW_PDFS}")
    require_pdfs()

    docling_bin = shutil.which("docling")
    if not docling_bin:
        raise SystemExit(
            "The docling CLI is not on PATH. It is installed by requirements.txt; "
            "in a checkout, activate the virtualenv first."
        )

    parse = ["scripts/parse_guidelines.py", "--run-docling", "--docling-bin", docling_bin]
    if args.ocr:
        parse.append("--docling-ocr")
    if args.force:
        parse.append("--force-docling")
    run("parse PDFs (Docling: reading order, tables, bounding boxes)", parse)

    if args.force or not CORPUS.exists():
        run("chunk into typed, citable units", ["scripts/chunk_docling.py"])
    else:
        print(f"\n=== chunk === already present, skipping ({CORPUS})")

    index = ["scripts/build_indexes.py"]
    index += ["--skip-dense"] if args.skip_dense else ["--dense-model", DENSE_MODEL]
    run("build lexical" + ("" if args.skip_dense else " and dense") + " indexes", index)

    # doc2query expansions are generated by an LLM and cached in the repository
    # data directory; the index over them is cheap to rebuild and is what
    # retrieval actually reads.
    if (DATA / "doc2query.jsonl").exists():
        run("index the generated clinician-voice questions",
            ["scripts/build_doc2query_index.py"])
    else:
        print("\n=== doc2query === no expansions cached; skipping.")
        print("    Retrieval still works. Generate them with scripts/build_doc2query.py")
        print("    (needs an API key). Without them, clinician-phrased questions score")
        print("    about 0.16 nDCG lower - see reports/ABLATION.md.")

    print("\nCorpus ready.")
    print(f"  chunks  : {CHUNKS}")
    print(f"  indexes : {INDEXES}")
    print("\nServe it with:  python scripts/demo_server.py")


if __name__ == "__main__":
    main()
